### ISSUE TITLE
Inserting the Clock

### ISSUE THREAD

**Issue by thunderhawk6630** [JohnRDOrazio/jQuery-Clock-Plugin#24]
I've linked the js files in the header, and created a <div> with an id of clock in the body. But I cannot get the clock to show in the browser.

Can you point me in the right direction?

**Comment by JohnRDOrazio** [comment]
Hello, have you linked jQuery first?

**Comment by thunderhawk6630** [comment]
After looking at your demo sites, I did not have the "$(document).ready(function(){" in there, so the code was not complete.

Full code to insert into your header for anyone else who's having trouble. It should look like:

<script type="text/javascript"> 
      $(document).ready(function(){  
		$("#clock").clock();
      }); 
</script>

Thanks,
