### ISSUE TITLE
Doesn't support IE 9?

### ISSUE THREAD

**Issue by erhuabushuo** [JohnRDOrazio/jQuery-Clock-Plugin#25]
Doesn't support IE 9?

**Comment by JohnRDOrazio** [comment]
Version 2.3.4 does not support IE9 because IE9 does not fully support the Performance Web API. You can use versions prior to 2.3.4 on IE9 or, if you would like to use version 2.3.4 on IE9, you can use the following polyfill before including the jQuery Clock script in your page:

```Javascript
<script>
(function (global) {

var
startTime = Date.now();

if (!global.performance) {
    global.performance = {};
}

global.performance.now = function () {
    return Date.now() - startTime;
};

}(this));
</script>
```
