### ISSUE TITLE
When you change your local date

### ISSUE THREAD

**Issue by jandres** [JohnRDOrazio/jQuery-Clock-Plugin#3]
When you use a server timestamp but change the local date, the clock changes its date too, but it adds the amount of minutes that you add to your local time.

Thanks

**Comment by JohnRDOrazio** [comment]
Sorry if I didn't look into this better back in 2012, I kind of left the project off without further testing. I took it up again recently (after 5 years!) and I saw what you are getting at: the System clock's timezone affects javascript's Date object which effectively doesn't reflect a server timestamp passed in.
I have looked into this and I have solved a lot of the wrinkles, now the jQuery Clock will solve for timezone differences so the jQuery clock is not affected by the system clock. It also is now independent from the system clock to the point that if you change the time on your system clock, the jQuery clock won't be affected at all.
